TranVanTai.DuongTuanDuy/TranVanTai.DuongTuanDuy/Controllers/TranVanTaiSearchController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TranVanTai.DuongTuanDuy.Models;
using System.Linq.Dynamic;
using System.Linq.Expressions;

namespace TranVanTai.DuongTuanDuy.Areas.Admin.Controllers
{
    public class TranVanTaiSearchController : Controller
    {
        SachOnlineEntities db = new SachOnlineEntities();
        // GET: Admin/Search
        public ActionResult Search(string strSearch)
        {
            ViewBag.Search = strSearch;
            if (!string.IsNullOrEmpty(strSearch))
            {
                var kq = from s in db.SACHes
                         join cd in db.CHUDEs on s.MaCD equals cd.MaCD
                         join nxb in db.NHAXUATBANs on s.MaNXB equals nxb.MaNXB
                         where s.TenSach.Contains(strSearch)
                            || s.MoTa.Contains(strSearch)
                            || cd.TenChuDe.Contains(strSearch)
                            || nxb.TenNXB.Contains(strSearch)
                         //orderby s.NgayCapNhat descending, s.SoLuongBan asrcending
                         select s;
                return View(kq);
            }
            return View();
        }
        public ActionResult SearchTheoDanhMuc(string strSearch = null, int maCD = 0)
        {
            // 1. Lưu từ khóa tìm kiếm ViewBag.Search = strSearch;

            //2.Tạo câu truy cơ bản
            var kq = db.SACHes.Select(b => b);
            //3. Tìm kiếm theo searchString
            if (!String.IsNullOrEmpty(strSearch))
                kq = kq.Where(b => b.TenSach.Contains(strSearch));

            //4. Tìm kiếm theo MaCD if (maCD != 0)
            {
                kq = kq.Where(b => b.CHUDE.MaCD == maCD);
            }
            //5. Tạo danh sách danh mục để hiển thị ở giao diện View thông qua DropDownList


            ViewBag.MaCD = new SelectList(db.CHUDEs, "MaCD", "TenChuDe"); // danh sách Chủ đề
            //ViewBag.cd = db.CHUDEs.ToList();
            return View(kq.ToList());
        }

        public ActionResult Group()
        {
            //var kq = from s in db.SACHes group s by s.MaCD;
            var kq = db.SACHes.GroupBy(s => s.MaCD);

            return View(kq);
        }
        public ActionResult ThongKe()
        {
            var rawResult = from s in db.SACHes
                            join cd in db.CHUDEs on s.MaCD equals cd.MaCD
                            group s by new { cd.MaCD, cd.TenChuDe } into g
                            select new
                            {
                                MaCD = g.Key.MaCD,
                                TenChuDe = g.Key.TenChuDe,
                                Count = g.Count(),
                                Sum = g.Sum(n => n.SoLuongBan),
                                Max = g.Max(n => n.SoLuongBan),
                                Avg = g.Average(n => n.SoLuongBan)
                            };

            // Now do the conversion in-memory
            var kq = rawResult.ToList().Select(g => new ReportInfo
            {
                Id = g.MaCD.ToString(),
                Name = g.TenChuDe,
                Count = g.Count,
                Sum = g.Sum,
                Max = g.Max,
                Avg = Convert.ToDecimal(g.Avg)
            });

            return View(kq);
        }
        public ActionResult SearchPhanTrang(int? page, string strSearch = null)
        {
            ViewBag.Search = strSearch;
            if (!string.IsNullOrEmpty(strSearch))
            {
                int iSize = 3;
                int iPageNumber = (page ?? 1);
                var kq = (from s in db.SACHes
                          where s.TenSach.Contains(strSearch) || s.MoTa.Contains(strSearch)
                          select s).ToList();
                return View(kq.ToPagedList(iPageNumber, iSize));
            }
            return View();
        }
        public ActionResult SearchPhanTrangTuyChon(int? size, int? page, string strSearch)
        {
            // 1. List để lấy nguồn cho ComboBox chọn số lượng sản phẩm
            var items = new List<SelectListItem>()
            {
                new SelectListItem { Text = "3", Value = "3" },
                new SelectListItem { Text = "5", Value = "5" },
                new SelectListItem { Text = "10", Value = "10" }
            };

            // 1.1 Giữ trạng thái kích thước trang được chọn trên DropDownList
            foreach (var item in items)
            {
                if (item.Value == size.ToString())
                {
                    item.Selected = true;
                }
            }

            // 1.2. Tạo các biến ViewBag
            ViewBag.Size = items; // ViewBag DropDownList
            ViewBag.CurrentSize = size; // Tạo biến kích thước trang hiện tại
            ViewBag.Search = strSearch;

            // 1.3. Mặc định 3 item trên 1 trang nếu không có giá trị
            int iSize = (size ?? 3);
            int iPageNumber = (page ?? 1);

            // 1.4. Kiểm tra nếu có từ khóa tìm kiếm
            if (!string.IsNullOrEmpty(strSearch))
            {
                var kq = (from s in db.SACHes
                          where s.TenSach.Contains(strSearch) || s.MoTa.Contains(strSearch)
                          select s).ToList();

                return View(kq.ToPagedList(iPageNumber, iSize));
            }

            // Nếu không có từ khóa tìm kiếm, trả về toàn bộ sách
            var allBooks = db.SACHes.ToList();
            return View(allBooks.ToPagedList(iPageNumber, iSize));
        }
        public ActionResult SearchPhanTrangSapXep(int? page, string sortProperty, string sortOrder = "*", string strSearch = null)
        {
            ViewBag.Search = strSearch;

            if (string.IsNullOrEmpty(strSearch))
            {
                strSearch = null;
            }

            int iSize = 3;
            int iPageNumber = (page ?? 1);

            // 1. Gán giá trị cho biến sortOrder
            if (sortOrder == "*") ViewBag.SortOrder = "desc";
            if (sortOrder == "desc") ViewBag.SortOrder = "*";
            if (sortOrder == "*") ViewBag.SortOrder = "asc";

            // Tạo thuộc tính sắp xếp mặc định là "Tên Sách"
            if (String.IsNullOrEmpty(sortProperty))
            {
                sortProperty = "TenSach";
            }

            // Gán giá trị cho biến sortProperty
            ViewBag.SortProperty = sortProperty;

            // Truy vấn
            var kq = from s in db.SACHes
                     where s.TenSach.Contains(strSearch) || s.MoTa.Contains(strSearch)
                     select s;

            // Sắp xếp tăng/giảm bằng phương thức OrderBy sử dụng trong thư viện Dynamic LINQ
            if (sortOrder == "desc")
            {
                kq = kq.OrderBy(sortProperty + " " + sortOrder);
            }
            else
            {
                kq = kq.OrderBy(sortProperty);
            }

            return View(kq.ToPagedList(iPageNumber, iSize));
        }

        

    }
}

TranVanTai.DuongTuanDuy/TranVanTai.DuongTuanDuy/Views/TranVanTaiSearch/Group.cshtml
@model IEnumerable<IGrouping<int?, TranVanTai.DuongTuanDuy.Models.SACH>>
@{
    ViewBag.Title = "Group";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h2>DANH SÁCH SÁCH THEO CHÚ ĐỀ</h2>
@foreach (var item in Model)
{
    <div>
        <h4 style="font-weight:bold; color:red;">MÃ CHÚ ĐÈ @item.Key</h4>
        <table border="1">
        <tr style="background-color: burlywood; font-weight:bold;">
            <td>Mã Sách</td>
            <td>Tên Sách</td>
            <td>Tên CD</td>
        </tr>
        @foreach (var sach in item)
        {
            <tr>
                <td>@sach.MaSach</td>
                <td>@sach.TenSach</td>
                <td>@sach.CHUDE.TenChuDe</td>
            </tr>
        }
        </table>
    </div>
}

TranVanTai.DuongTuanDuy/TranVanTai.DuongTuanDuy/Views/TranVanTaiSearch/Search.cshtml
@model IEnumerable<TranVanTai.DuongTuanDuy.Models.SACH>

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
@if (ViewBag.Message != null)
{
    <div class="alert alert-info">
        @ViewBag.Message
    </div>
}

@if (Model != null)
{

}

@{
    if (Model != null)
    {
        if (Model.Count() > 0)
        {
            <h2>Kết quả tìm kiếm: có @Model.Count() cuốn sách với từ khóa: @ViewBag.Search</h2>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.MaSach)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TenSach)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MoTa)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AnhBia)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NgayCapNhat)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SoLuongBan)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.GiaBan)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MaCD)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MaNXB)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaSach)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenSach)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MoTa)
                        </td>
                        <td>
                            <img src="~/Images/@item.AnhBia" width="50" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NgayCapNhat)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoLuongBan)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GiaBan)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaCD)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaNXB)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                            <a href="@Url.Action("ChiTietSach", "TranVanTai", new {id = item.MaSach})">Chi tiết sách</a> |
                            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                        </td>
                    </tr>
                }

            </table>
        }
        else
        {
            <h2>Khong tim thay ket qua nao voi tu khoa @ViewBag.Search</h2>
        }
    }
}

TranVanTai.DuongTuanDuy/TranVanTai.DuongTuanDuy/Views/TranVanTaiSearch/SearchPhanTrang.cshtml
@using TranVanTai.DuongTuanDuy.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>
@{
    ViewBag.Title = "SearchPhanTrang";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

@using (Html.BeginForm("SearchPhanTrang", "TranVanTaiSearch", FormMethod.Get))
{
    <p>
        <input type="text" name="strSearch" value="@ViewBag.Search" placeholder="Nhập sản phẩm cần tìm..." size="100" />
        <input type="submit" value="Tìm kiếm" />
    </p>
}

@{
    if (Model != null)
    {
        if (Model.Count() > 0)
        {
            <h2>Kết quả tìm kiếm cuốn sách với từ khóa: @ViewBag.Search</h2>
            <table class="table">
                <tr>
                    <th>Tên sách</th>
                    <th>Ảnh bìa</th>
                    <th>Ngày cập nhật</th>
                    <th>Số lượng bán</th>
                    <th>Giá</th>
                    <th>Tên chủ đề</th>
                    <th>Tên NXB</th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenSach)
                        </td>
                        <td>
                            <img src="~/Images/@item.AnhBia" width="50" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NgayCapNhat)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoLuongBan)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GiaBan)
                        </td>
                        <td>
                            @item.CHUDE.TenChuDe
                        </td>
                        <td>
                            @item.NHAXUATBAN.TenNXB
                        </td>
                        <td>
                            <a href="@Url.Action("ChiTietSach", "TranTanPhuc", new { id = item.MaSach })">Chi Tiết</a>
                        </td>
                    </tr>
                }

            </table>

            <div>Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</div>

            <div class="MenuTrang">
                @Html.PagedListPager(Model, page => Url.Action("SearchPhanTrang", new { page = page, strSearch = ViewBag.Search }))
            </div>

            <style>
                .MenuTrang {
                    display: inline;
                    text-align: center;
                }
            </style>
        }
        else
        {
            <h2>Khong tim thay ket qua nao voi tu khoa @ViewBag.Search</h2>
        }
    }
}

TranVanTai.DuongTuanDuy/TranVanTai.DuongTuanDuy/Views/TranVanTaiSearch/SearchPhanTrangSapXep.cshtml
@using System.Linq.Dynamic;
@using System.Linq.Expressions;
@using TranVanTai.DuongTuanDuy.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>
@{
    ViewBag.Title = "SearchPhanTrangSapXep";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>SearchPhanTrangSapXep</h2>

@using (Html.BeginForm("SearchPhanTrangSapXep", "TranVanTaiSearch", FormMethod.Get))
{
    <input type="text" name="strSearch" value="@ViewBag.Search" placeholder="Nhập sản phẩm cần tìm..." size="100" />
    <input type="submit" value="Tìm kiếm" />
}

<h2>KẾT QUẢ TÌM KIẾM</h2>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Tên sách", "SearchPhanTrangSapXep",
                          new { sortProperty = "TenSach", sortOrder = ViewBag.SortOrder, strSearch = ViewBag.Search })
        </th>
        <th>Ảnh bìa</th>
        <th>
            @Html.ActionLink("Ngày cập nhật", "SearchPhanTrangSapXep",
                          new { sortProperty = "NgayCapNhat", sortOrder = ViewBag.SortOrder, strSearch = ViewBag.Search })
        </th>
        <th>
            @Html.ActionLink("Số lượng bán", "SearchPhanTrangSapXep",
                          new { sortProperty = "SoluongBan", sortOrder = ViewBag.SortOrder, strSearch = ViewBag.Search })
        </th>
        <th>
            @Html.ActionLink("Giá bán", "SearchPhanTrangSapXep",
                           new { sortProperty = "GiaBan", sortOrder = ViewBag.SortOrder, strSearch = ViewBag.Search })
        </th>
        <th>
            Ten chu de
        </th>
        <th>
            Ten NXB
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenSach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnhBia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayCapNhat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuongBan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaBan)
            </td>
            <td>
                @item.CHUDE.TenChuDe
            </td>
            <td>
                @item.NHAXUATBAN.TenNXB
            </td>
            <td>
                <a href="@Url.Action("ChiTietSach", "TranVanTai", new { id = item.MaSach })">Chi Tiết</a>
            </td>
        </tr>
    }

</table>

<!-- Tạo liên kết các trang -->
<div>Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</div>

<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("SearchPhanTrangSapXep",
            new { page = page, sortProperty = ViewBag.SortProperty, sortOrder = ViewBag.SortOrder, strSearch = ViewBag.Search }))
</div>

<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }
</style>

TranVanTai.DuongTuanDuy/TranVanTai.DuongTuanDuy/Views/TranVanTaiSearch/SearchPhanTrangTuyChon.cshtml
@using TranVanTai.DuongTuanDuy.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>
@{
    ViewBag.Title = "SearchPhanTrangTuyChon";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>SearchPhanTrangTuyChon</h2>

@using (Html.BeginForm("SearchPhanTrangTuyChon", "TranVanTaiSearch", FormMethod.Get))
{
    <input type="text" name="strSearch" value="@ViewBag.Search" placeholder="Nhập sản phẩm cần tìm..." size="100" />
    <input type="submit" value="Tìm kiếm" />
}
@using (Html.BeginForm("SearchPhanTrangTuyChon", "TranVanTaiSearch", FormMethod.Get))
{
    <label>Kích thước trang:</label>
    @Html.DropDownList("size", (List<SelectListItem>)ViewBag.Size, new { onchange = "this.form.submit();" })

    @Html.Hidden("page", (object)ViewBag.Page)
    @Html.Hidden("strSearch", (object)ViewBag.Search)
}

<!-- Tạo liên kết các trang -->

@{
    if (Model != null)
    {
        if (Model.Count() > 0)
        {
            <h2>Kết quả tìm kiếm cuốn sách với từ khóa: @ViewBag.Search</h2>
            <table class="table">
                <tr>
                    <th>Tên sách</th>
                    <th>Ảnh bìa</th>
                    <th>Ngày cập nhật</th>
                    <th>Số lượng bán</th>
                    <th>Giá</th>
                    <th>Tên chủ đề</th>
                    <th>Tên NXB</th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenSach)
                        </td>
                        <td>
                            <img src="~/Images/@item.AnhBia" width="50" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NgayCapNhat)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoLuongBan)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GiaBan)
                        </td>
                        <td>
                            @item.CHUDE.TenChuDe
                        </td>
                        <td>
                            @item.NHAXUATBAN.TenNXB
                        </td>
                        <td>
                            <a href="@Url.Action("ChiTietSach", "TranVanTai", new { id = item.MaSach })">Chi Tiết</a>
                        </td>
                    </tr>
                }

            </table>

            <div>Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</div>

            <div class="MenuTrang">
                @Html.PagedListPager(Model, page => Url.Action("SearchPhanTrangTuyChon",
                                new { size = ViewBag.CurrentSize, page = page, strSearch = ViewBag.Search }))
            </div>

            <style>
                .MenuTrang {
                    display: inline;
                    text-align: center;
                }
            </style>
        }
        else
        {
            <h2>Khong tim thay ket qua nao voi tu khoa @ViewBag.Search</h2>
        }
    }
}

TranVanTai.DuongTuanDuy/TranVanTai.DuongTuanDuy/Views/TranVanTaiSearch/SearchTheoDanhMuc.cshtml
@using TranVanTai.DuongTuanDuy.Models
@model IEnumerable<TranVanTai.DuongTuanDuy.Models.SACH>


@{
    ViewBag.Title = "SearchTheoDanhMuc";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
@{
    //List<CHUDE> cd = (List<CHUDE>)ViewBag.cd;
}
<style>
    .macd {
        width: 200px;
    }
</style>
@using (Html.BeginForm("SearchTheoDanhMuc", "TranVanTaiSearch", FormMethod.Get))
{
    <p>
        Chủ đề:
        @Html.DropDownList("maCD", null, htmlAttributes: new { @class = "macd" }) @*
            <select name="maCD">
            <option value="0">Tất cả chủ đề</option> @foreach (var item in cd)
            {
            <option value="@item.MaCD">@item.TenChuDe</option>
            }
            </select>
        *@
        Tên sản phẩm:
        <input type="text" name="strSearch" value="@ViewBag.Search" placeholder="Nhập sản phẩm cần tìm..." size="30" />
        <input type="submit" value="Tìm kiếm" />

    </p>
}


@{
    if (Model != null)
    {
        <h2>KẾT QUẢ TÌM</h2>

        <table class="table">

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TenSach)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MoTa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AnhBia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NgayCapNhat)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SoLuongBan)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GiaBan)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MaCD)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MaNXB)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenSach)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MoTa)
                    </td>
                    <td>
                        <img src="~/Images/@item.AnhBia" width="50" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgayCapNhat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoLuongBan)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GiaBan)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaCD) @*<br />@item.CHUDE.TenChuDe*@


                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaNXB)
                    </td>
                    <td>
                        @*Html.ActionLink("Details", "BookDetail", "SachOnline", new { MaSach = item.MaSach })*@
                        <a href="@Url.Action("BookDetail", "SachOnline", new {MaSach = item.MaSach})">Detail</a>
                    </td>
                </tr>
            }

        </table>


    }
}

TranVanTai.DuongTuanDuy/TranVanTai.DuongTuanDuy/Views/TranVanTaiSearch/ThongKe.cshtml
@model IEnumerable<TranVanTai.DuongTuanDuy.Models.ReportInfo>

@{
    ViewBag.Title = "ThongKe";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>THỐNG KÊ SỐ ĐẦU SÁCH THEO CHỦ ĐỀ</h2>

<table border="1">
    <tr style="background-color:burlywood; font-weight:bold;">
        <td>Mã CD</td>
        <td>Tên Chủ Đề</td>
        <td>Số Đầu Sách</td>
        <td>Tổng Số Sách</td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Count</td>
            <td>@item.Sum</td>
        </tr>
    }
</table>